apiVersion: apps/v1
kind: Deployment
metadata:
 name: nodejs-pipeline
 labels:
   app: nodejs-pipeline
spec:
 selector:
  matchLabels:
   app: nodejs-pipeline
 template:
  metadata:
   labels:
    app: nodejs-pipeline
  spec:
   containers:
   - image: ip_address_of_the_machine:5000/nodejs-api-image:latest
     name: nodejs-api
     imagePullPolicy: Always
     ports:
       - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: nodejs-pipeline-svc
spec:
    ports:
    - name: “nodejs-pipeline”
      targetPort: 8080
      port: 8080
      nodePort: 30253
      protocol: TCP
    selector:
       app: nodejs_pipeline
    type: NodePort
